# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 69b2829c8ca1e163c889726625e01d0ec763bd4201bc6b8fb5a7cf394bca17a0798c3f01d123ac50118a17991b26904c662ac9432f4ad6be52258a3de7056ac3

test:
  secret_key_base: d11777aecb412f50c4c0ff1e3e2d7d8a7234abb5e793034261fbad9bd62959b1f2b291003061b260adcbe8a0f468078c3dcea11ea35ccb25d0c3ab930ca8423d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
